### PR TITLE
Gui menu dropdowns

### PR DESCRIPTION
**Pull request by mfriendc**
sorted all parts into categories for ease of use and clutter-reduction

### CODE REVIEW

**Review by innovation-plantation — COMMENTED** [review]
What is this legacy behavior?

**Comment by mfriendc** [comment]
to recap my previous message: the "legacy behavior" is that the old version's window would start at the size indicated

the only "bad thing" that happens when you leave the resize thing out is that the window is created at 100% of the screen's size because the window wraps to the canvas edges, I put the resize in to start the window a bit smaller, and I thought the original size was adequate and if anyone cared how big it was before the change, it wouldn't be different afterward so they wouldn't notice, I suppose

**Comment by innovation-plantation** [comment]
OK, if it's not important, take it out to reduce code clutter. It will be consistent with non-legacy behavior then I'll pull the changes.

**Comment by mfriendc** [comment]
alright, I'll remove it. keep in mind the pull request for gui/canvas-size and the one for gui/dropdowns should be separate, I hope

sorry for the messy commit list here, I realized I didn't want to commit the size thing onto my master copy so I had to undo it to keep my branches separate, unfortunately it leaves the old commits in the history because I couldn't just undo the commit

**Comment by mfriendc** [comment]
I don't know how to resubmit a pull request, I think it has to be denied first so I can retry?

**Comment by innovation-plantation** [comment]
Don;t worry I'll just merge the pull request and remove the line and push it back myself.

**Pull request merged**
